# Generated by Django 3.1.4 on 2020-12-25 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='drink_id',
        ),
        migrations.AddField(
            model_name='categories',
            name='menu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starbucks.menu'),
        ),
    ]
