# Generated by Django 3.1.4 on 2020-12-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks', '0002_auto_20201225_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='menu_id',
            new_name='menu',
        ),
    ]
