# Generated by Django 3.1.4 on 2020-12-26 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks', '0003_auto_20201225_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starbucks.categories'),
        ),
    ]
