# Generated by Django 3.1.4 on 2020-12-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks', '0004_drinks_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
