# Generated by Django 3.1.4 on 2020-12-26 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks', '0005_drinks_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy_drink',
            name='allergy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starbucks.allergy'),
        ),
        migrations.AddField(
            model_name='allergy_drink',
            name='drink_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starbucks.drinks'),
        ),
        migrations.AddField(
            model_name='images',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starbucks.drinks'),
        ),
        migrations.AddField(
            model_name='nutritions',
            name='drink_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starbucks.drinks'),
        ),
    ]
