# Generated by Django 3.1.4 on 2020-12-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks', '0006_auto_20201226_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy_drink',
            old_name='drink_id',
            new_name='drink',
        ),
    ]
