# Generated by Django 3.1.4 on 2020-12-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks', '0008_auto_20201226_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy',
            name='drinks',
        ),
    ]
