# Generated by Django 3.1.4 on 2020-12-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks', '0009_remove_allergy_drinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='drinks',
            field=models.ManyToManyField(to='starbucks.Drinks'),
        ),
    ]
