# Generated by Django 3.1.4 on 2021-01-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks', '0011_auto_20201226_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='starbucks.allergy')),
                ('drink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='starbucks.drinks')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_serving_kcal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sodium_mg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('saturated_fat_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sugars_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('protein_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('caffeine_mg', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('size_ml', models.IntegerField(default=0)),
                ('size_fluid_ounce', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nutrition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='starbucks.nutrition')),
            ],
        ),
        migrations.DeleteModel(
            name='nutritions',
        ),
        migrations.AddField(
            model_name='drinks',
            name='nutrition',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='starbucks.nutrition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drinks',
            name='allergy',
            field=models.ManyToManyField(through='starbucks.AllergyDrink', to='starbucks.Allergy'),
        ),
    ]
